on:
  release:
    types: 
      - published

jobs:
  build:
    strategy:
      matrix:
        runtime:
          - linux-arm
          - linux-arm64
          - ubuntu-x64
          - win-arm64
          - win-x64
          - win-x86
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - run: |
          dotnet publish src/EdcHost/EdcHost.csproj -c Release -o bin \
          --sc false -r ${{ matrix.runtime }} -p:DebugType=none \
          -p:PublishSingleFile=true

      - run: |
          cp CHANGELOG.md LICENSE README.md bin

      - uses: actions/upload-artifact@v3
        with:
          name: edchost-${{ matrix.runtime }}-${{ github.sha }}
          path: bin

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - linux-arm
          - linux-arm64
          - ubuntu-x64
          - win-arm64
          - win-x64
          - win-x86
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: edchost-${{ matrix.runtime }}-${{ github.sha }}
          path: bin

      - run: |
          cp CHANGELOG.md LICENSE README.md bin/

      - name: Pack artifact (Windows)
        if: startsWith(matrix.runtime, 'win')
        run: |
          cd bin
          zip -r ../edchost-${{ matrix.runtime }}.zip *
          cd ..
  
      - name: Pack artifact (Others)
        if: startsWith(matrix.runtime, 'win') == false
        run: |
          cd bin
          chmod +x EdcHost
          tar -czvf ../edchost-${{ matrix.runtime }}.tar.gz *
          cd ..

      - name: Upload artifact to release (Windows)
        if: startsWith(matrix.runtime, 'win')
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            edchost-${{ matrix.runtime }}.zip

      - name: Upload artifact to release (Others)
        if: startsWith(matrix.runtime, 'win') == false
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            edchost-${{ matrix.runtime }}.tar.gz
